# fc-pregmod:build
# Compiling needs node and Go installed

# Start with the base golang image, cause installing go is way to complicated
FROM golang

RUN curl -sL https://deb.nodesource.com/setup_19.x | bash
RUN apt-get install -y nodejs
