/* eslint-disable camelcase */

/**
 * @type {FC.SlaveTemplate[]}
 */
App.Data.HeroSlaves.DD = [
	{
		ID: 800001,
		slaveName: "Marylynne",
		birthName: "Tyson",
		genes: "XY",
		origin: "$He is a life-long house slave who has always tried to be the perfect woman, despite $his dick.",
		actualAge: 34,
		physicalAge: 34,
		visualAge: 34,
		ovaryAge: 34,
		health: {condition: 20},
		devotion: 100,
		race: "white",
		origSkin: "white",
		hLength: 60,
		hStyle: "neat",
		waist: -55,
		boobs: 1000,
		natural: {boobs: 400},
		areolae: 1,
		butt: 5,
		lips: 35,
		vagina: -1,
		preg: -2,
		dick: 2,
		anus: 3,
		prostate: 1,
		balls: 1,
		scrotum: 1,
		skill: {oral: 35, anal: 100, penetrative: 35},
		intelligenceImplant: 30,
		attrXX: 40,
		attrXY: 40,
		fetish: "buttslut",
		fetishKnown: 1,
		custom: {desc: "$He is extremely self-conscious about $his dick."},
		sexualFlaw: "shamefast",
		behavioralQuirk: "insecure"
	},
	{
		ID: 800002,
		slaveName: "Alyssa",
		birthName: "Alyssa",
		genes: "XY",
		assignment: Job.HOUSE,
		actualAge: 21,
		physicalAge: 21,
		visualAge: 21,
		ovaryAge: 21,
		health: {condition: -30},
		devotion: 60,
		race: "white",
		origHColor: "blonde",
		pubicHColor: "blonde",
		origSkin: "pale",
		hLength: 10,
		hStyle: "neat",
		boobs: 300,
		butt: 1,
		vagina: -1,
		preg: -2,
		dick: 2,
		anus: 1,
		prostate: 1,
		balls: 1,
		scrotum: 1,
		attrXX: 40,
		attrXY: 40,
		fetishKnown: 1,
		faceShape: "androgynous"
	},
	{
		ID: 800003,
		slaveName: "Adrian",
		birthName: "Adrian",
		genes: "XY",
		actualAge: 21,
		physicalAge: 21,
		visualAge: 21,
		ovaryAge: 21,
		health: {condition: 20, tired: 10},
		devotion: 75,
		hLength: 60,
		hStyle: "neat",
		boobs: 400,
		butt: 2,
		vagina: -1,
		preg: -2,
		dick: 3,
		anus: 1,
		prostate: 1,
		balls: 1,
		scrotum: 1,
		skill: {oral: 15, anal: 15, penetrative: 15},
		attrXX: 40,
		attrXY: 40,
		fetish: "buttslut",
		fetishKnown: 1,
		behavioralFlaw: "odd"
	},
	{
		ID: 800004,
		slaveName: "Lola",
		birthName: "Lola",
		genes: "XY",
		actualAge: 27,
		physicalAge: 27,
		visualAge: 27,
		ovaryAge: 27,
		health: {condition: 20},
		devotion: 35,
		height: 175,
		race: "white",
		origSkin: "white",
		hLength: 60,
		hStyle: "neat",
		boobs: 1000,
		natural: {boobs: 300},
		boobsImplant: 600,
		boobsImplantType: "normal",
		butt: 4,
		buttImplant: 2,
		buttImplantType: "normal",
		vagina: -1,
		preg: -2,
		dick: 3,
		anus: 3,
		prostate: 1,
		balls: 1,
		scrotum: 1,
		skill: {oral: 15, anal: 15},
		aphrodisiacs: 1,
		addict: 10,
		intelligence: -30,
		attrXX: 40,
		attrXY: 40,
		fetish: "submissive",
		fetishKnown: 1
	},
	{
		ID: 800005,
		slaveName: "Amanda",
		birthName: "Amanda",
		genes: "XY",
		origin: "$He was raised as a girl despite $his gargantuan dick to be a truly unique slave.",
		actualAge: 17,
		physicalAge: 17,
		visualAge: 17,
		ovaryAge: 17,
		health: {condition: 20},
		height: 152,
		origHColor: "black",
		hLength: 60,
		hStyle: "neat",
		boobs: 500,
		butt: 3,
		vagina: -1,
		preg: -2,
		dick: 5,
		anus: 1,
		prostate: 1,
		balls: 3,
		scrotum: 3,
		intelligence: 20,
		intelligenceImplant: 30,
		attrXX: 80,
		attrXY: 40,
		fetishKnown: 1
	},
	{
		ID: 800006,
		slaveName: "'Mrs.' Maria",
		birthName: "Maria",
		genes: "XY",
		origin: "$He was once a successful drug lord, but was turned into $his current self after making too many enemies.",
		actualAge: 28,
		physicalAge: 28,
		visualAge: 28,
		ovaryAge: 28,
		health: {condition: 100},
		devotion: 75,
		muscles: 20,
		height: 175,
		race: "white",
		origHColor: "blonde",
		pubicHColor: "blonde",
		override_Skin: 1,
		origSkin: "spray tanned",
		hLength: 10,
		boobs: 1000,
		natural: {boobs: 400},
		boobsImplant: 600,
		boobsImplantType: "normal",
		lips: 55,
		lipsImplant: 10,
		vagina: -1,
		preg: -2,
		dick: 5,
		anus: 2,
		prostate: 1,
		balls: 2,
		scrotum: 2,
		skill: {oral: 100, anal: 100, penetrative: 65},
		intelligence: 100,
		intelligenceImplant: 30,
		attrXX: 40,
		attrXY: 40,
		fetishKnown: 1,
		piercing: {nipple: {weight: 1}, genitals: {weight: 2, smart: true}},
		clitSetting: "anal",
		brand: {"left testicle": "a brand of a former master"},
		stampTat: "$He has a fairly generic tramp stamp.",
		career: "a gang leader"
	},
	{
		ID: 800007,
		slaveName: "Sugar",
		birthName: "Sugar",
		genes: "XY",
		actualAge: 24,
		physicalAge: 24,
		visualAge: 24,
		ovaryAge: 24,
		health: {condition: 20},
		height: 175,
		race: "white",
		eye: {origColor: "blue"},
		origHColor: "platinum blonde",
		origSkin: "pale",
		hLength: 60,
		hStyle: "neat",
		waist: -55,
		boobs: 1400,
		natural: {boobs: 200},
		boobsImplant: 1200,
		boobsImplantType: "fillable",
		butt: 5,
		buttImplant: 4,
		buttImplantType: "fillable",
		lips: 55,
		lipsImplant: 2,
		vagina: -1,
		preg: -2,
		dick: 5,
		anus: 1,
		prostate: 1,
		balls: 1,
		scrotum: 1,
		skill: {oral: 100, anal: 100},
		clothes: "slutty jewelry",
		intelligence: -90,
		intelligenceImplant: 30,
		attrXX: 40,
		attrXY: 40,
		fetish: "cumslut",
		fetishKnown: 1,
		custom: {desc: "$He is as dumb as a bag of hammers."}
	},
	{
		ID: 800008,
		slaveName: "Bella",
		birthName: "Bella",
		genes: "XY",
		origin: "$He grew up in a rich and deviant household, surrounded by but never a part of bizarre and unusual sex acts.",
		actualAge: 19,
		physicalAge: 19,
		visualAge: 19,
		ovaryAge: 19,
		health: {condition: 20},
		devotion: 10,
		race: "white",
		origHColor: "blonde",
		pubicHColor: "blonde",
		origSkin: "white",
		hLength: 10,
		boobs: 300,
		butt: 1,
		vagina: -1,
		preg: -2,
		dick: 2,
		prostate: 1,
		balls: 1,
		scrotum: 1,
		clothes: "a slave gown",
		intelligence: 30,
		intelligenceImplant: 30,
		attrXX: 40,
		attrXY: 40,
		fetishKnown: 1,
		behavioralFlaw: "arrogant"
	},
	{
		ID: 800009,
		slaveName: "Julia",
		birthName: "Julia",
		genes: "XY",
		origin: "$He was homeless and willing to do anything for food, which in the end resulted in $him becoming a slave.",
		health: {condition: 20},
		devotion: 30,
		race: "white",
		origSkin: "white",
		hLength: 10,
		hStyle: "messy",
		boobs: 300,
		butt: 1,
		vagina: -1,
		preg: -2,
		dick: 3,
		anus: 2,
		prostate: 1,
		balls: 2,
		scrotum: 2,
		skill: {oral: 35, anal: 35, penetrative: 15},
		clothes: "a slave gown",
		intelligence: -20,
		attrXX: 40,
		attrXY: 40,
		fetishKnown: 1,
		custom: {desc: "$He has beautiful eyes and some scars."},
		scar: {
			"right breast": {
				burn: 0,
				chain: 0,
				cutting: 0,
				exotic: 0,
				generic: 1,
				menacing: 0,
				whip: 0
			},
		},
		arm: {
			right: {
				scar: {
					"right arm": {
						burn: 0,
						chain: 0,
						cutting: 0,
						exotic: 0,
						generic: 1,
						menacing: 0,
						whip: 0
					},
				},
			},
		},
		leg: {
			left: {
				scar: {
					"left buttock": {
						burn: 0,
						chain: 0,
						cutting: 0,
						exotic: 0,
						generic: 1,
						menacing: 0,
						surgical: 0,
						whip: 0
					},
					"left thigh": {
						burn: 0,
						chain: 0,
						cutting: 0,
						exotic: 0,
						generic: 1,
						menacing: 0,
						surgical: 0,
						whip: 0
					},
				},
			},
		},
	},
	{
		ID: 800010,
		slaveName: "Lily",
		birthName: "Lily",
		genes: "XY",
		actualAge: 20,
		physicalAge: 20,
		visualAge: 20,
		ovaryAge: 20,
		health: {condition: 20},
		devotion: -60,
		race: "white",
		origHColor: "black",
		pubicHColor: "black",
		origSkin: "white",
		hLength: 10,
		hStyle: "neat",
		boobs: 300,
		butt: 1,
		vagina: -1,
		preg: -2,
		dick: 3,
		prostate: 1,
		balls: 2,
		scrotum: 2,
		clothes: "a slave gown",
		attrXX: 40,
		attrXY: 40,
		fetishKnown: 1,
		behavioralFlaw: "bitchy"
	},
	{
		ID: 800011,
		slaveName: "Harry",
		birthName: "Harry",
		genes: "XY",
		actualAge: 20,
		physicalAge: 20,
		visualAge: 20,
		ovaryAge: 20,
		health: {condition: 20},
		devotion: 25,
		height: 175,
		heightImplant: 1,
		race: "white",
		eye: {origColor: "blue"},
		origHColor: "blonde",
		pubicHColor: "blonde",
		origSkin: "white",
		hLength: 25,
		hStyle: "neat",
		boobs: 300,
		butt: 5,
		face: 15,
		faceImplant: 15,
		lipsTat: "permanent makeup",
		vagina: -1,
		preg: -2,
		dick: 2,
		anus: 2,
		prostate: 1,
		balls: 1,
		scrotum: 1,
		skill: {oral: 15, anal: 15, penetrative: 15},
		clothes: "attractive lingerie",
		intelligence: -20,
		attrXX: 40,
		attrXY: 40,
		fetish: "cumslut",
		fetishKnown: 1
	},
	{
		ID: 800012,
		slaveName: "Jen",
		birthName: "Jen",
		genes: "XY",
		actualAge: 20,
		physicalAge: 20,
		visualAge: 20,
		ovaryAge: 20,
		health: {condition: 20},
		devotion: 40,
		height: 175,
		race: "white",
		origHColor: "dark brown",
		pubicHColor: "dark brown",
		origSkin: "white",
		hLength: 40,
		hStyle: "bun",
		boobs: 300,
		butt: 5,
		vagina: -1,
		preg: -2,
		dick: 3,
		prostate: 1,
		balls: 1,
		scrotum: 1,
		clothes: "attractive lingerie",
		attrXX: 40,
		attrXY: 40,
		fetish: "cumslut",
		fetishKnown: 1,
		career: "a librarian",
		intelligence: 35,
		intelligenceImplant: 30
	},
	{
		ID: 800013,
		slaveName: "Kai",
		birthName: "Mordecai",
		genes: "XY",
		actualAge: 23,
		physicalAge: 23,
		visualAge: 23,
		ovaryAge: 23,
		health: {condition: 20},
		devotion: 60,
		height: 191,
		nationality: "Russian",
		race: "white",
		origHColor: "black",
		pubicHColor: "black",
		origSkin: "white",
		hLength: 140,
		hStyle: "luxurious",
		waist: -55,
		heels: 1,
		boobs: 1000,
		natural: {boobs: 400},
		boobsImplant: 600,
		boobsImplantType: "normal",
		lactation: 1,
		lactationDuration: 2,
		butt: 5,
		buttImplant: 3,
		buttImplantType: "normal",
		lips: 35,
		lipsImplant: 10,
		vagina: 1,
		preg: -2,
		dick: 5,
		anus: 1,
		prostate: 1,
		balls: 2,
		scrotum: 2,
		skill: {oral: 35, anal: 15, penetrative: 15},
		clothes: "restrictive latex",
		intelligence: 25,
		intelligenceImplant: 30,
		attrXX: 40,
		attrXY: 40,
		fetishKnown: 1,
		custom: {tattoo: "$He has many girly tattoos.", desc: "$He likes hair play."},
		piercing: {nipple: {weight: 2}, lips: {weight: 1}, navel: {weight: 1}}
	},
	{
		ID: 800014,
		slaveName: "Mackenzie",
		birthName: "Mackenzie",
		genes: "XY",
		actualAge: 21,
		physicalAge: 21,
		visualAge: 21,
		ovaryAge: 21,
		health: {condition: 40},
		devotion: 60,
		race: "white",
		nationality: "Irish",
		markings: "freckles",
		eye: {origColor: "blue"},
		origHColor: "red",
		pubicHColor: "red",
		origSkin: "pale",
		hStyle: "braided",
		hLength: 60,
		boobs: 1800,
		natural: {boobs: 500},
		shoulders: -1,
		waist: -20,
		hips: 1,
		butt: 4,
		lips: 35,
		vagina: -1,
		preg: -2,
		dick: 3,
		anus: 1,
		prostate: 1,
		balls: 2,
		scrotum: 2,
		skill: {oral: 15, anal: 15, penetrative: 15},
		intelligence: 98,
		intelligenceImplant: 30,
		attrXX: 40,
		attrXY: 40,
		fetish: "submissive",
		fetishKnown: 1,
		piercing: {nipple: {weight: 1}},
		custom: {desc: "$He has a slim and perfectly feminine frame except for $his big feet and ears. $He's very intelligent and well learned."}
	},
	{
		ID: 800015,
		slaveName: "Rachel",
		birthName: "Rachel",
		genes: "XY",
		origin: "$He volunteered to become a slave when $he turned 18.",
		health: {condition: 20},
		devotion: 100,
		height: 155,
		race: "white",
		origHColor: "blonde",
		pubicHColor: "blonde",
		origSkin: "pale",
		hLength: 25,
		hStyle: "neat",
		waist: -55,
		boobs: 600,
		natural: {boobs: 300},
		butt: 2,
		face: 15,
		lips: 35,
		vagina: -1,
		preg: -2,
		dick: 2,
		prostate: 1,
		balls: 1,
		scrotum: 1,
		anusTat: "bleached",
		intelligence: 20,
		attrXX: 40,
		attrXY: 40,
		fetish: "buttslut"
	},
	{
		ID: 800016,
		slaveName: "Nikole",
		birthName: "Nikole",
		genes: "XY",
		actualAge: 19,
		physicalAge: 19,
		visualAge: 19,
		ovaryAge: 19,
		health: {condition: 80},
		devotion: 100,
		nationality: "Irish",
		race: "white",
		markings: "freckles",
		eye: {origColor: "green"},
		origHColor: "red",
		pubicHColor: "red",
		origSkin: "pale",
		hLength: 60,
		hStyle: "ponytail",
		boobs: 200,
		natural: {boobs: 400},
		butt: 5,
		lips: 35,
		vagina: -1,
		preg: -2,
		dick: 5,
		anus: 1,
		prostate: 1,
		balls: 3,
		scrotum: 3,
		anusTat: "bleached",
		skill: {oral: 100, anal: 100, penetrative: 100},
		attrXX: 40,
		attrXY: 40,
		fetishKnown: 1,
		custom: {tattoo: "$He has a tattoo of a black widow's hourglass pattern on $his ballsack."}
	},
	{
		ID: 800017,
		slaveName: "Exta",
		birthName: "Exta",
		genes: "XY",
		actualAge: 21,
		physicalAge: 21,
		visualAge: 21,
		ovaryAge: 21,
		health: {condition: 20},
		devotion: 60,
		muscles: 20,
		height: 190,
		race: "white",
		eye: {origColor: "brown"},
		origHColor: "blonde",
		pubicHColor: "blonde",
		origSkin: "white",
		hLength: 15,
		hStyle: "in a boyish cut",
		boobs: 300,
		butt: 1,
		vagina: -1,
		preg: -2,
		dick: 2,
		prostate: 1,
		balls: 1,
		anusTat: "bleached",
		skill: {oral: 15, penetrative: 15, combat: 15},
		intelligence: 30,
		attrXX: 40,
		attrXY: 40,
		fetishKnown: 1,
		sexualFlaw: "shamefast",
		career: "a businessman",
		custom: {tattoo: "$He has a raised circuitry pattern on the nape of $his neck."}
	},
	{
		ID: 800018,
		slaveName: "Martin",
		birthName: "Martin",
		genes: "XY",
		actualAge: 19,
		physicalAge: 19,
		visualAge: 19,
		ovaryAge: 19,
		health: {condition: 20},
		devotion: -55,
		muscles: 20,
		height: 190,
		race: "white",
		eye: {origColor: "bright blue"},
		origHColor: "white",
		pubicHColor: "white",
		origSkin: "extremely pale",
		hLength: 15,
		hStyle: "in a boyish cut",
		waist: -55,
		boobs: 100,
		natural: {boobs: 300},
		butt: 4,
		face: 55,
		vagina: -1,
		preg: -2,
		dick: 3,
		prostate: 1,
		balls: 3,
		scrotum: 3,
		anusTat: "bleached",
		skill: {combat: 65, penetrative: 35},
		intelligence: 30,
		intelligenceImplant: 30,
		attrXX: 40,
		attrXY: 40,
		fetish: "submissive",
		behavioralFlaw: "arrogant",
		custom: {desc: "An iron-willed, recently captured figure of a prominent anti-Free City guerrilla party, $he still clings strongly to traditional beliefs on Man's natural good, economic restriction, and monogamy. Excitable, girly, and sweet in comparison to $his natural sister, Elisa, $he has a lovely singing voice. $He prays quite often, if allowed to."},
		mother: -9997,
		father: -9996,
		sexualFlaw: "hates penetration"
	},
	{
		ID: 800019,
		slaveName: "Steven",
		birthName: "Steven",
		genes: "XY",
		origin: "$He was forced into slavery due to extreme debt.",
		actualAge: 31,
		physicalAge: 31,
		visualAge: 31,
		ovaryAge: 31,
		health: {condition: 20},
		devotion: -55,
		weight: 40,
		origHColor: "blonde",
		pubicHColor: "blonde",
		race: "white",
		hLength: 0,
		hStyle: "shaved",
		boobs: 200,
		natural: {boobs: 400},
		butt: 3,
		vagina: -1,
		preg: -2,
		dick: 3,
		prostate: 1,
		balls: 3,
		scrotum: 3,
		anusTat: "bleached",
		skill: {oral: 15, penetrative: 15},
		attrXX: 40,
		attrXY: 40,
		fetishKnown: 1,
		behavioralFlaw: "arrogant",
		sexualFlaw: "hates penetration"
	},
	{
		ID: 800020,
		slaveName: "Selene",
		birthName: "Selene",
		genes: "XY",
		origin: "Once $he was an arcology security officer, lured to aphrodisiacs addiction and feminized by $his boss (and former wife), to whom $he was sold as a slave to satisfy her spousal maintenance after divorce.",
		actualAge: 32,
		physicalAge: 32,
		visualAge: 32,
		ovaryAge: 32,
		health: {condition: 20},
		devotion: 40,
		muscles: 20,
		height: 175,
		race: "latina",
		eye: {origColor: "ice blue"},
		origHColor: "ashen with black streaks",
		pubicHColor: "ashen",
		origSkin: "brown",
		hLength: 30,
		hStyle: "neat",
		waist: -55,
		boobs: 1400,
		natural: {boobs: 400},
		butt: 1,
		face: 55,
		lips: 35,
		vagina: -1,
		preg: -2,
		dick: 5,
		anus: 2,
		prostate: 1,
		balls: 2,
		scrotum: 2,
		anusTat: "bleached",
		skill: {anal: 100, combat: 65, penetrative: 35},
		addict: 50,
		intelligence: 20,
		intelligenceImplant: 30,
		attrXX: 40,
		attrXY: 40,
		fetish: "buttslut",
		fetishKnown: 1,
		behavioralFlaw: "odd",
		piercing: {
			dick: {weight: 1}, ear: {weight: 1}, navel: {weight: 1}, areola: {weight: 2, desc: "$He has a large police badge made of polished silver pinned right to the skin with several barbell piercings just above $his left nipple."}
		},
		custom: {desc: "$He wears two pairs of handcuffs as bracelets (one pair on each wrist); the handcuff keyholes are welded, so they cannot be unlocked and removed in any normal way."},
		career: "a security guard"
	},
	{
		ID: 800021,
		slaveName: "'Buns' Jones",
		birthName: "Jones",
		genes: "XY",
		devotion: 31,
		nationality: "Chinese",
		race: "asian",
		override_H_Color: 1,
		origHColor: "black",
		hColor: "dark brown with bleached highlights",
		override_Skin: 1,
		origSkin: "spray tanned",
		hLength: 60,
		hStyle: "in a braided ponytail",
		waist: -55,
		boobs: 200,
		natural: {boobs: 400},
		butt: 8,
		lips: 35,
		vagina: -1,
		vaginaTat: "rude words",
		preg: -2,
		dick: 3,
		prostate: 1,
		balls: 2,
		scrotum: 2,
		anusTat: "flowers",
		makeup: 1,
		nails: 1,
		shouldersTat: "tribal patterns",
		armsTat: "rude words",
		stampTat: "rude words",
		skill: {oral: 100, penetrative: 15, entertainment: 15},
		clothes: "a slutty outfit",
		collar: "pretty jewelry",
		shoes: "heels",
		intelligence: 30,
		attrXX: 40,
		attrXY: 40,
		fetish: "buttslut",
		fetishKnown: 1,
		piercing: {ear: {weight: 1}},
		custom: {desc: "A palm sized ring adorns the end of $his braid, perfect for grabbing and pulling during any occasion."}
	},
	{
		ID: 800022,
		slaveName: "Mistress Izzy",
		birthName: "Isabella",
		genes: "XY",
		health: {condition: 70},
		devotion: 100,
		race: "white",
		eye: {origColor: "black"},
		origHColor: "sparkling and shiny golden red",
		pubicHColor: "blonde",
		override_Skin: 1,
		origSkin: "sun tanned",
		hLength: 60,
		hStyle: "in thick, heavy braids",
		waist: -100,
		boobs: 9200,
		natural: {boobs: 500},
		boobsImplant: 6000,
		boobsImplantType: "advanced fillable",
		boobsTat: "bovine patterns",
		lactation: 2,
		lactationDuration: 2,
		counter: {milk: 3010},
		butt: 8,
		buttImplant: 1,
		buttImplantType: "normal",
		buttTat: "bovine patterns",
		face: 55,
		faceImplant: 65,
		lips: 55,
		lipsImplant: 2,
		lipsTat: "bovine patterns",
		vagina: 2,
		vaginaTat: "bovine patterns",
		preg: -2,
		anus: 2,
		dick: 5,
		prostate: 1,
		balls: 3,
		scrotum: 2,
		anusTat: "bovine patterns",
		makeup: 2,
		nails: 2,
		leg: {right: {brand: {"right buttock": "SLUT"}}},
		shouldersTat: "bovine patterns",
		armsTat: "bovine patterns",
		legsTat: "bovine patterns",
		stampTat: "bovine patterns",
		skill: {
			vaginal: 35,
			oral: 100,
			anal: 100,
			penetrative: 15,
			whoring: 100,
			entertainment: 35
		},
		collar: "leather with cowbell",
		shoes: "heels",
		intelligence: 20,
		energy: 100,
		attrXX: 40,
		attrXY: 40,
		fetishKnown: 1,
		piercing: {
			nipple: {weight: 2}, lips: {weight: 2}, tongue: {weight: 2}, vagina: {weight: 2}, anus: {weight: 2}, ear: {weight: 2}, nose: {weight: 2}, eyebrow: {weight: 2}, navel: {weight: 2}, genitals: {weight: 2, smart: true}
		},
		clitSetting: "boobs",
		custom: {
			tattoo: "$He has tattoos of teasing, enticing messages begging others to come taste $his addictive milk.",
			desc: "$His musky milky aura drives men and women around $him giggly and dumb with lust."
		},
		horn: "cow horns"
	},
	{
		ID: 800023,
		slaveName: "Joan",
		birthName: "Mila",
		genes: "XY",
		actualAge: 28,
		physicalAge: 28,
		visualAge: 28,
		ovaryAge: 28,
		health: {condition: 100},
		devotion: 25,
		weight: 20,
		height: 175,
		race: "white",
		origHColor: "dark brown",
		pubicHColor: "brown",
		origSkin: "pale",
		hLength: 30,
		hStyle: "ponytail",
		pubicHStyle: "bushy",
		boobs: 650,
		areolae: 2,
		lactation: 2,
		lactationDuration: 2,
		butt: 7,
		lips: 35,
		vagina: -1,
		preg: -2,
		dick: 4,
		prostate: 1,
		balls: 5,
		scrotum: 4,
		makeup: 1,
		nails: 1,
		skill: {penetrative: 15, entertainment: 35},
		clothes: "cutoffs and a t-shirt",
		collar: "pretty jewelry",
		shoes: "heels",
		intelligence: -40,
		intelligenceImplant: 30,
		attrXX: 80,
		attrXY: 40,
		fetishKnown: 1,
		behavioralFlaw: "odd",
		piercing: {
			nipple: {weight: 1}, anus: {weight: 1}, ear: {weight: 1}, genitals: {weight: 2, smart: true}
		},
		clitSetting: "off",
		custom: {
			tattoo: "$He has a blood red, faux brand tattoo on $his left ass cheek.",
			desc: "$He has a nearly faded pockmark on the skin above $his left eyebrow, the last reminder of $his awkward past."
		}
	},
	{
		ID: 800024,
		slaveName: "Aisha",
		birthName: "Aicha",
		genes: "XY",
		origin: "$He sold $himself into slavery to escape a life of boredom.",
		health: {condition: -20},
		devotion: 45,
		height: 155,
		heightImplant: -1,
		race: "middle eastern",
		override_Eye_Color: 1,
		eye: {origColor: "blue"},
		override_H_Color: 1,
		override_Brow_H_Color: 1,
		override_Arm_H_Color: 1,
		override_Pubic_H_Color: 1,
		origHColor: "peachy fading into a red ombre at the bottom",
		eyebrowHColor: "red",
		pubicHColor: "red",
		underArmHColor: "red",
		origSkin: "light",
		hLength: 30,
		hStyle: "hime",
		waist: -55,
		boobs: 250,
		natural: {boobs: 450},
		butt: 3.5,
		face: 55,
		faceImplant: 65,
		vagina: -1,
		preg: -2,
		anus: 1,
		dick: 5,
		dickTat: "flowers",
		prostate: 1,
		balls: 2,
		scrotum: 2,
		anusTat: "flowers",
		brand: {"back": "your initials"},
		skill: {
			oral: 15, anal: 15, penetrative: 15, entertainment: 15
		},
		clothes: "a comfortable bodysuit",
		collar: "pretty jewelry",
		shoes: "heels",
		intelligence: -30,
		attrXX: 40,
		attrXY: 40,
		piercing: {anus: {weight: 1}, ear: {weight: 1}, genitals: {weight: 2, smart: true}},
		clitSetting: "off",
		custom: {
			tattoo: "$He has tattooed petals trailing from the nape of $his neck down $his back, ending between $his butt cheeks.",
			desc: "$His red pubic hair is waxed into the shape of a heart. $He has bright blue eyeshadow on $his bottom lids."
		},
		pubicHStyle: "waxed"
	},
	{
		ID: 800025,
		slaveName: "Laura",
		birthName: "Rolan",
		genes: "XY",
		prestige: 1,
		prestigeDesc: "$He is a high-ranking spy who was captured while trying to obtain secrets about the defenses of one the Free Cities.",
		health: {condition: -10},
		devotion: 5,
		height: 155,
		race: "middle eastern",
		override_H_Color: 1,
		override_Eye_Color: 1,
		eye: {origColor: "blue"},
		origHColor: "white",
		pubicHColor: "white",
		origSkin: "dark",
		hLength: 60,
		hStyle: "tied in a bun using a pearl chain",
		heels: 1,
		boobs: 200,
		natural: {boobs: 400},
		butt: 2,
		vagina: -1,
		preg: -2,
		bellyAccessory: "a corset",
		dick: 2,
		prostate: 1,
		balls: 2,
		scrotum: 2,
		makeup: 1,
		nails: 1,
		skill: {oral: 15, penetrative: 35},
		collar: "pretty jewelry",
		shoes: "heels",
		intelligence: 100,
		intelligenceImplant: 30,
		attrXX: 40,
		attrXY: 40,
		piercing: {ear: {weight: 1}, navel: {weight: 1}},
		career: "a spy"
	},
	{
		ID: 800026,
		slaveName: "'Dragon Goddess' Chae-won",
		genes: "XY",
		birthName: "Chae-won",
		origin: "$He is a former Kkangpae gang member who was sold into slavery by $his former boss as a punishment.",
		prestige: 1,
		prestigeDesc: "$He is a famed Free Cities whore, and commands top prices.",
		actualAge: 26,
		physicalAge: 26,
		visualAge: 26,
		ovaryAge: 26,
		health: {condition: 50},
		devotion: 31,
		muscles: 50,
		height: 155,
		nationality: "Korean",
		race: "asian",
		override_H_Color: 1,
		origHColor: "black",
		hColor: "onyx black and rainbow-streaked",
		override_Skin: 1,
		origSkin: "sun tanned",
		hLength: 60,
		hStyle: "styled in high chignon resembling a traditional Japanese geisha's Shimada hairstyle, with plenty of decorated hairpins",
		waist: -55,
		boobs: 6000,
		natural: {boobs: 300},
		boobsImplant: 3000,
		boobsImplantType: "advanced fillable",
		nipples: "huge",
		butt: 4.5,
		face: 55,
		faceImplant: 15,
		lips: 35,
		lipsTat: "permanent makeup",
		vagina: -1,
		preg: -2,
		anus: 1,
		dick: 5,
		prostate: 1,
		balls: 4,
		scrotum: 4,
		anusTat: "bleached",
		nails: 3,
		legsTat: "flowers",
		stampTat: "flowers",
		skill: {
			oral: 100, anal: 100, penetrative: 65, whoring: 100
		},
		clothes: "a slave gown",
		collar: "pretty jewelry",
		shoes: "heels",
		intelligence: -3,
		intelligenceImplant: 30,
		energy: 100,
		attrXX: 40,
		attrXY: 40,
		fetishKnown: 1,
		behavioralFlaw: "arrogant",
		piercing: {tongue: {weight: 1}, ear: {weight: 1}},
		custom: {
			tattoo: "$He has two neon-blue butterflies tattooed on $his right temple and one more right above $his right eyebrow; a bright blue, luminescent tattoo of an oriental dragon is intertwining with floral tattoos on $his right leg.",
			desc: "$He is almost never seen without $his long, thin, lavishly decorated smoking pipe, either holding it in hand, or carrying it tucked in $his chignon."
		},
		career: "a gang member"
	},
	{
		ID: 800027,
		slaveName: "Bailey",
		birthName: "Bryan",
		genes: "XY",
		origin: "$He was sold to your predecessor by $his husband to pay off his extreme debt.",
		actualAge: 22,
		physicalAge: 22,
		visualAge: 22,
		ovaryAge: 22,
		health: {condition: 50},
		devotion: -50,
		nationality: "American",
		race: "white",
		eye: {origColor: "blue"},
		origHColor: "black",
		pubicHColor: "black",
		origSkin: "fair",
		hLength: 50,
		hStyle: "styled up in schoolgirl pigtails with bangs",
		boobs: 700,
		natural: {boobs: 400},
		boobsImplant: 400,
		boobsImplantType: "normal",
		butt: 2,
		lips: 35,
		vagina: -1,
		preg: -2,
		anus: 1,
		dick: 2,
		prostate: 1,
		balls: 2,
		scrotum: 2,
		makeup: 1,
		nails: 1,
		skill: {oral: 15},
		clothes: "a slutty maid outfit",
		shoes: "heels",
		intelligenceImplant: 30,
		attrXX: 40,
		attrXY: 40,
		fetish: "submissive",
		fetishKnown: 1,
		piercing: {ear: {weight: 1}}
	},
	{
		ID: 800028,
		slaveName: "'Mistress' Ingrid",
		birthName: "Ingrid",
		genes: "XY",
		actualAge: 42,
		physicalAge: 42,
		visualAge: 42,
		ovaryAge: 42,
		health: {condition: 100},
		devotion: 100,
		muscles: 20,
		height: 190,
		race: "white",
		nationality: "Norwegian",
		eye: {origColor: "blue"},
		override_H_Color: 1,
		origHColor: "black",
		hColor: "onyx black",
		origSkin: "pale",
		hLength: 110,
		hStyle: "neat with Nordic braids throughout",
		waist: -55,
		boobs: 800,
		butt: 5,
		face: 55,
		lips: 35,
		preg: -2,
		dick: 4,
		prostate: 1,
		balls: 4,
		scrotum: 4,
		ovaries: 1,
		makeup: 2,
		nails: 2,
		skill: {
			vaginal: 35,
			oral: 35,
			anal: 15,
			penetrative: 35,
			whoring: 35,
			entertainment: 35,
			combat: 15
		},
		clothes: "a slave gown",
		collar: "pretty jewelry",
		shoes: "boots",
		intelligence: 25,
		intelligenceImplant: 30,
		energy: 100,
		attrXX: 40,
		attrXY: 40,
		fetishKnown: 1,
		piercing: {genitals: {weight: 2, smart: true}},
		clitSetting: "off",
		custom: {desc: "$He has the style of Gothic royalty, and the demeanor to match."}
	},
	{
		ID: 800029,
		slaveName: "'Demon Whore' Yuzuki",
		birthName: "Yuri",
		genes: "XY",
		origin: "$His origins are unknown, but rumor has it that $he is a literal demon.",
		actualAge: 19,
		physicalAge: 19,
		visualAge: 19,
		ovaryAge: 19,
		health: {condition: 60},
		devotion: 90.4,
		muscles: 20,
		height: 190,
		nationality: "Japanese",
		race: "asian",
		eye: {origColor: "green", left: {pupil: "demonic"}, right: {pupil: "demonic"}},
		origHColor: "black",
		pubicHColor: "black",
		origSkin: "pale",
		hLength: 60,
		hStyle: "neat",
		pubicHStyle: "in a strip",
		waist: -100,
		boobs: 10000,
		natural: {boobs: 550},
		boobsImplant: 4800,
		boobsImplantType: "advanced fillable",
		areolae: 2,
		lactation: 2,
		lactationDuration: 2,
		butt: 9,
		face: 55,
		faceImplant: 65,
		lips: 35,
		vagina: 1,
		anus: 1,
		dick: 5,
		prostate: 1,
		balls: 5,
		scrotum: 4,
		ovaries: 1,
		makeup: 2,
		nails: 2,
		skill: {
			vaginal: 15,
			oral: 100,
			anal: 15,
			penetrative: 100,
			whoring: 15,
			entertainment: 15,
			combat: 35
		},
		clothes: "a string bikini",
		collar: "pretty jewelry",
		shoes: "boots",
		attrXX: 40,
		attrXY: 40,
		fetish: "humiliation",
		fetishKnown: 1,
		piercing: {genitals: {weight: 2, smart: true}},
		clitSetting: "humiliation"
	},
	{
		ID: 800030,
		slaveName: "Fuckmeat",
		birthName: "Alva",
		genes: "XY",
		prestige: 1,
		prestigeDesc: "$He is a famed Free Cities slut, and can please anyone.",
		actualAge: 19,
		physicalAge: 19,
		visualAge: 19,
		ovaryAge: 19,
		health: {condition: 100},
		devotion: 100,
		muscles: 20,
		height: 145,
		race: "white",
		nationality: "Swedish",
		eye: {origColor: "blue"},
		origHColor: "blonde",
		pubicHColor: "blonde",
		origSkin: "pale",
		hLength: 0,
		hStyle: "shaved",
		pubicHStyle: "bushy",
		boobs: 1700,
		natural: {boobs: 450},
		boobsTat: "rude words",
		butt: 8,
		buttTat: "rude words",
		face: 55,
		lips: 35,
		vagina: -1,
		vaginaTat: "rude words",
		preg: -2,
		anus: 3,
		dick: 2,
		dickTat: "rude words",
		prostate: 1,
		balls: 1,
		scrotum: 2,
		anusTat: "rude words",
		makeup: 3,
		nails: 3,
		brand: {"cheek": "a penis symbol"},
		shouldersTat: "rude words",
		armsTat: "rude words",
		legsTat: "rude words",
		stampTat: "rude words",
		skill: {
			oral: 100,
			anal: 100,
			whoring: 100,
			entertainment: 100,
			combat: 35
		},
		diet: "muscle building",
		clothes: "harem gauze",
		collar: "heavy gold",
		shoes: "boots",
		energy: 100,
		attrXX: 40,
		attrXY: 40,
		fetishStrength: 0,
		fetishKnown: 1,
		custom: {tattoo: "$He has a swastika tattooed on $his ballsack."}
	},
	{
		ID: 800031,
		slaveName: "Caroline",
		birthName: "Carl",
		prestige: 1,
		prestigeDesc: "$He was once a rising Free Cities politician who argued for compulsory female enslavement, but $he became an addict, fell into debt, and was subsequently enslaved.",
		genes: "XY",
		actualAge: 44,
		physicalAge: 44,
		visualAge: 44,
		ovaryAge: 44,
		health: {condition: 60},
		devotion: 90,
		height: 145,
		heightImplant: -1,
		race: "white",
		nationality: "French",
		eye: {origColor: "blue"},
		origHColor: "blonde",
		pubicHColor: "blonde",
		override_Skin: 1,
		origSkin: "spray tanned",
		hLength: 90,
		hStyle: "neat",
		waist: -55,
		heels: 1,
		boobs: 1100,
		natural: {boobs: 400},
		boobsImplant: 400,
		boobsImplantType: "normal",
		areolae: 1,
		butt: 4,
		buttImplant: 2,
		buttImplantType: "normal",
		face: 55,
		faceImplant: 65,
		lips: 55,
		lipsImplant: 2,
		vagina: 1,
		vaginaLube: 1,
		preg: -2,
		anus: 2,
		anusTat: "bleached",
		makeup: 3,
		nails: 1,
		legsTat: "degradation",
		stampTat: "degradation",
		skill: {
			vaginal: 100,
			oral: 100,
			anal: 100,
			penetrative: 35,
			whoring: 15,
			entertainment: 35
		},
		drugs: "breast injections",
		addict: 1,
		clothes: "slutty jewelry",
		collar: "tight steel",
		intelligence: -90,
		intelligenceImplant: 30,
		attrXY: 40,
		fetish: "humiliation",
		behavioralFlaw: "arrogant",
		piercing: {nipple: {weight: 1}, ear: {weight: 1}, navel: {weight: 1}},
		custom: {
			tattoo: "$He has a tattoo down $his left arm, which reads 'Once a tall, muscular, handsome man with a big dick and big balls.'",
			desc: "Since becoming a slave $he has been turned into a little bimbo."
		}
	},
];

/**
 * @type {FC.SlaveTemplate[]}
 */
App.Data.HeroSlaves.DDextreme = [
	{
		ID: 800032,
		slaveName: "Fjola",
		birthName: "Fjola",
		genes: "XY",
		origin: "$He was born into a slave ring that practiced heavy hormone manipulation to alter slaves from a very young age.",
		actualAge: 21,
		physicalAge: 21,
		visualAge: 21,
		ovaryAge: 21,
		health: {condition: 20},
		devotion: 10,
		weight: 20,
		height: 160,
		race: "white",
		eye: {
			origColor: "grey"
		},
		origHColor: "black",
		pubicHColor: "black",
		origSkin: "pale",
		hLength: 30,
		hStyle: "curly",
		boobs: 1000,
		natural: {boobs: 800},
		butt: 3,
		vagina: 1,
		preg: -2,
		dick: 2,
		anus: 1,
		skill: {
			oral: 15,
			anal: 15
		},
		intelligence: -40,
		intelligenceImplant: 30,
		attrXX: 40,
		attrXY: 40,
		fetish: "submissive",
		fetishKnown: 1,
		custom: {desc: "$He has a small scar on $his cheek, and many larger ones on $his back."},
		scar: {
			"left cheek": {
				burn: 0,
				chain: 0,
				cutting: 0,
				exotic: 0,
				generic: 1,
				menacing: 0,
				surgical: 0,
				whip: 0
			},
			"back": {
				burn: 0,
				chain: 0,
				cutting: 0,
				exotic: 0,
				generic: 2,
				menacing: 0,
				surgical: 0,
				whip: 0
			},
		}
	},

	/* tsundere, grey eyes, unhappy to be herm*/
	/* Changed eye color, added customDesc and origin -BoneyM*/

	{
		ID: 800033,
		slaveName: "Alex",
		birthName: "Alex",
		genes: "XY",
		origin: "$He was given a sex change in a freak laboratory mix-up, and sold $himself into slavery out of desperation due to a lack of any way to prove $his identity.",
		health: {condition: 20},
		height: 175,
		race: "white",
		origSkin: "pale",
		hLength: 60,
		hStyle: "neat",
		boobs: 400,
		preg: -2,
		skill: {penetrative: 15},
		attrXX: 40,
		attrXY: 40,
		sexualFlaw: "hates penetration",
		prostate: 1
	},

	/* MtF*/
	/* Made a post-op to match the bio as closely as possible in-universe, added origin, added hates penetration. -BoneyM*/

	{
		ID: 800034,
		slaveName: "Janine",
		birthName: "Janine",
		genes: "XY",
		origin: "$He was enslaved after $he fell into debt to you.",
		actualAge: 27,
		physicalAge: 27,
		visualAge: 27,
		ovaryAge: 27,
		health: {condition: 90},
		devotion: 100,
		nationality: "German",
		eye: {origColor: "blue"},
		origHColor: "golden blonde",
		pubicHColor: "blonde",
		origSkin: "pale",
		hLength: 10,
		hStyle: "beautifully framing $his face",
		waist: -55,
		boobs: 500,
		butt: 3.5,
		face: 15,
		lips: 35,
		vagina: -1,
		preg: -2,
		dick: 1,
		anusTat: "bleached",
		skill: {oral: 100, penetrative: 35},
		clothes: "a penitent nuns habit",
		collar: "tight steel",
		shoes: "heels",
		attrXX: 40,
		attrXY: 40,
		fetish: "submissive",
		fetishKnown: 1,
		markings: "beauty mark",
		custom: {desc: "$He has a beauty mark just above $his lip, on an otherwise flawless face."}
	},

	{
		ID: 800035,
		slaveName: "Buck",
		birthName: "Buck",
		genes: "XY",
		origin: "$He was a soldier before being enslaved.",
		actualAge: 23,
		physicalAge: 23,
		visualAge: 23,
		ovaryAge: 23,
		health: {condition: 90},
		devotion: -100,
		muscles: 50,
		height: 190,
		race: "white",
		eye: {origColor: "blue"},
		origHColor: "black",
		pubicHColor: "black",
		override_Skin: 1,
		origSkin: "spray tanned",
		hLength: 0,
		prostate: 1,
		hStyle: "shaved",
		waist: -55,
		boobs: 100,
		natural: {boobs: 450},
		butt: 1,
		face: 15,
		vagina: -1,
		preg: -2,
		dick: 5,
		analArea: 1,
		balls: 3,
		scrotum: 3,
		anusTat: "bleached",
		skill: {combat: 65, penetrative: 15},
		intelligence: -40,
		intelligenceImplant: 30,
		attrXX: 40,
		attrXY: 40,
		behavioralFlaw: "bitchy",
		career: "a soldier",
		piercing: {
			nipple: {weight: 1}, ear: {weight: 1}, nose: {weight: 1}, navel: {weight: 1}
		}
	},

	/* dickskilled*/

	{
		ID: 800036,
		slaveName: "'Udders' Erika",
		birthName: "Erika",
		genes: "XY",
		actualAge: 28,
		physicalAge: 28,
		visualAge: 28,
		ovaryAge: 28,
		health: {condition: 90},
		devotion: 55,
		height: 145,
		race: "white",
		eye: {origColor: "blue"},
		origSkin: "fair",
		hLength: 60,
		hStyle: "neat",
		pubicHStyle: "in a strip",
		boobs: 1250,
		natural: {boobs: 750},
		areolae: 2,
		boobsTat: "bovine patterns",
		lactation: 2,
		lactationDuration: 2,
		butt: 2,
		buttTat: "bovine patterns",
		lips: 55,
		lipsImplant: 10,
		lipsTat: "bovine patterns",
		vagina: -1,
		vaginaTat: "bovine patterns",
		preg: -3,
		anus: 2,
		dick: 1,
		dickTat: "bovine patterns",
		prostate: 1,
		anusTat: "bovine patterns",
		shouldersTat: "bovine patterns",
		armsTat: "bovine patterns",
		legsTat: "bovine patterns",
		stampTat: "bovine patterns",
		skill: {oral: 100, anal: 100, entertainment: 35},
		collar: "leather with cowbell",
		attrXX: 40,
		attrXY: 40,
		fetish: "boobs",
		fetishKnown: 1,
		voice: 0,
		piercing: {nose: {weight: 2}, genitals: {weight: 2, smart: true}},
		clitSetting: "boobs",
		custom: {desc: "Though $his vocal cords have been altered to keep $him from speaking, $he is still capable of the occasional moo."}
	},
	{
		ID: 800037,
		slaveName: "Danny 'The D'",
		slaveSurname: "Ildoe",
		birthName: "Danny 'The D'",
		birthSurname: "Ildoe",
		origin: "Born without limbs and abandoned by $his parents, $he was taken in by a posh family, given a massive cock, and trained to be the wealthy lady's perfect living sex toy.",
		actualAge: 28,
		visualAge: 28,
		physicalAge: 28,
		ovaryAge: 28,
		health: {condition: 100},
		devotion: 100,
		muscles: 50,
		height: 94,
		race: "white",
		eye: {origColor: "blue"},
		origHColor: "black",
		pubicHColor: "black",
		override_Skin: 1,
		origSkin: "spray tanned",
		hLength: 10,
		hStyle: "neat",
		waist: 55,
		boobs: 50,
		natural: {boobs: 300},
		hips: -1,
		butt: 0,
		face: 45,
		vagina: -1,
		preg: 0,
		dick: 6,
		balls: 10,
		scrotum: 7,
		prostate: 2,
		anusTat: "bleached",
		energy: 95,
		intelligenceImplant: 30,
		attrXX: 100,
		attrXY: 0,
		skill: {oral: 95, penetrative: 95},
		fetish: "submissive",
		fetishKnown: 1,
		behavioralQuirk: "advocate"
	},
];

/*
{slaveName = "STANDARD", birthName = "STANDARD", ID = i++, actualAge = 21, physicalAge = 21, visualAge = 21, ovaryAge = 21, health: {condition: 20}, devotion = 60, origSkin = "white", origHColor = "blonde", pubicHColor = "blonde", hLength = 20, boobs = 300, butt = 1, vagina = -1, preg = -2, dick = 2, anus = 1, balls = 1, scrotum = 1, anusTat = "bleached", skill.oral = 15, skill.anal = 15, attrXX = 40, attrXY = 40, fetishKnown = 1},
*/
