/* eslint-disable camelcase */

/**
 * @type {FC.SlaveTemplate[]}
 */
App.Data.HeroSlaves.DF = [
	{
		ID: 700001,
		slaveName: "Cherry",
		birthName: "Cherry",
		health: {condition: 20},
		devotion: 75,
		race: "white",
		actualAge: 18,
		physicalAge: 18,
		visualAge: 18,
		ovaryAge: 18,
		eye: {origColor: "light brown"},
		pubicHColor: "black",
		origSkin: "white",
		origHColor: "black",
		hStyle: "neat",
		hLength: 60,
		pubicHStyle: "waxed",
		boobs: 500,
		butt: 3,
		lips: 35,
		vagina: 1,
		vaginaLube: 1,
		preg: -2,
		ovaries: 1,
		skill: {vaginal: 35},
		attrXY: 40,
		fetish: "submissive",
		fetishKnown: 1,
		lipsTat: "Two cherries are tattooed on $his left cheek.",
		buttTat: "Two cherries are tattooed on $his right butt cheek.",
		piercing: {nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}},
		counter: {birthsTotal: 1}
	},
	/* vag implant, vibe nips*/
	{
		ID: 700002,
		slaveName: "Strawberry",
		birthName: "Strawberry",
		actualAge: 30,
		physicalAge: 30,
		visualAge: 30,
		ovaryAge: 30,
		health: {condition: 20},
		devotion: 40,
		race: "white",
		height: 175,
		eye: {origColor: "dark brown"},
		origHColor: "blonde",
		pubicHColor: "blonde",
		override_Skin: 1,
		origSkin: "sun tanned",
		hStyle: "neat",
		hLength: 60,
		pubicHStyle: "waxed",
		waist: -55,
		boobs: 1000,
		natural: {boobs: 600},
		boobsImplant: 400,
		boobsImplantType: "normal",
		butt: 5,
		buttImplant: 2,
		buttImplantType: "normal",
		lips: 35,
		lipsImplant: 10,
		vagina: 2,
		vaginaLube: 1,
		preg: -2,
		anus: 2,
		ovaries: 1,
		skill: {vaginal: 35, oral: 35, anal: 35},
		attrXY: 40,
		fetish: "humiliation",
		fetishKnown: 1,
		lipsTat: "Strawberries are tattooed on $his left cheek.",
		buttTat: "Strawberries are tattooed on $his right buttock.",
		piercing: {nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}},
		counter: {birthsTotal: 2}
	},
	/* vibe nips, muscles*/
	{
		ID: 700003,
		slaveName: "Melon",
		birthName: "Melon",
		actualAge: 23,
		physicalAge: 23,
		visualAge: 23,
		ovaryAge: 23,
		health: {condition: 20},
		devotion: 50,
		height: 175,
		race: "white",
		eye: {origColor: "blue"},
		origHColor: "red",
		pubicHColor: "red",
		override_Skin: 1,
		origSkin: "sun tanned",
		hLength: 10,
		hStyle: "neat",
		pubicHStyle: "waxed",
		boobs: 1800,
		natural: {boobs: 1000},
		boobsImplant: 800,
		boobsImplantType: "fillable",
		butt: 4,
		lips: 35,
		lipsImplant: 10,
		vagina: 2,
		vaginaLube: 1,
		preg: -2,
		anus: 2,
		ovaries: 1,
		skill: {vaginal: 15, oral: 100, anal: 15},
		attrXY: 40,
		fetish: "submissive",
		fetishKnown: 1,
		lipsTat: "Watermelons are tattooed on $his face.",
		buttTat: "Watermelons are tattooed on $his buttocks.",
		teeth: "removable",
		piercing: {
			nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}, lips: {weight: 2}
		},
		counter: {birthsTotal: 1}
	},
	/* vibe nips, saliva implant*/
	{
		ID: 700004,
		slaveName: "Carambola",
		birthName: "Carambola",
		actualAge: 25,
		physicalAge: 25,
		visualAge: 25,
		ovaryAge: 25,
		health: {condition: 20},
		devotion: 90,
		race: "white",
		height: 175,
		eye: {origColor: "light green"},
		origHColor: "dark blonde",
		pubicHColor: "dark blonde",
		override_Skin: 1,
		origSkin: "sun tanned",
		hLength: 60,
		hStyle: "in curly pigtails",
		pubicHStyle: "waxed",
		boobs: 650,
		butt: 8,
		buttImplant: 4,
		buttImplantType: "fillable",
		lips: 35,
		vagina: 1,
		vaginaLube: 1,
		preg: -2,
		anus: 3,
		ovaries: 1,
		skill: {vaginal: 15, oral: 15, anal: 100},
		attrXY: 40,
		fetish: "buttslut",
		fetishKnown: 1,
		lipsTat: "Carambolas — starfruits — are tattooed on $his face.",
		buttTat: "Carambolas — starfruits — are tattooed on $his buttocks.",
		piercing: {
			nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}, tongue: {weight: 1}
		},
		clothes: "no clothing",
		collar: "bell collar",
		heels: 1
	},
	/* vibe nips, saliva implant lube*/
	{
		ID: 700005,
		slaveName: "Banana",
		actualAge: 28,
		physicalAge: 28,
		visualAge: 28,
		ovaryAge: 28,
		health: {condition: 20},
		devotion: 65,
		race: "latina",
		origHColor: "black",
		pubicHColor: "black",
		origSkin: "brown",
		boobs: 400,
		butt: 5,
		lips: 35,
		vagina: 2,
		vaginaLube: 1,
		preg: -2,
		anus: 2,
		ovaries: 1,
		skill: {
			vaginal: 35, oral: 100, anal: 35, penetrative: 15
		},
		attrXY: 40,
		fetish: "submissive",
		fetishKnown: 1,
		lipsTat: "Bananas are tattooed on $his face.",
		buttTat: "Bananas are tattooed on $his buttocks.",
		teeth: "removable",
		piercing: {nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}},
		hips: 1,
		labia: 2,
		clit: 1,
		bald: 1,
		hLength: 0,
		hStyle: "bald",
		pubicHStyle: "bald",
		underArmHStyle: "bald",
		intelligence: -30
	},
	/* vibe nips, big pusslips+clit*/
	{
		ID: 700006,
		slaveName: "Green Grape",
		birthName: "Green Grape",
		health: {condition: 20},
		devotion: 40,
		actualAge: 18,
		physicalAge: 18,
		visualAge: 18,
		ovaryAge: 18,
		race: "mixed race",
		eye: {origColor: "green"},
		origHColor: "black",
		pubicHColor: "black",
		origSkin: "pale",
		hLength: 60,
		hStyle: "neat",
		pubicHStyle: "waxed",
		boobs: 650,
		butt: 4,
		vagina: 1,
		vaginaLube: 1,
		preg: -2,
		anus: 1,
		ovaries: 1,
		skill: {vaginal: 35, oral: 35, anal: 35},
		attrXX: 80,
		attrXY: 40,
		fetishKnown: 1,
		lipsTat: "Green grapes are tattooed on $his face.",
		buttTat: "Green grapes are tattooed on $his buttocks.",
		mother: -9995,
		father: -9994,
		piercing: {nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}},
		intelligence: -60
	},
	/* vibe nips, implant link to sister*/
	{
		ID: 700007,
		slaveName: "Purple Grape",
		birthName: "Purple Grape",
		actualAge: 23,
		physicalAge: 23,
		visualAge: 23,
		ovaryAge: 23,
		health: {condition: 20},
		devotion: 40,
		race: "mixed race",
		eye: {origColor: "black"},
		origHColor: "black",
		pubicHColor: "black",
		origSkin: "brown",
		hLength: 60,
		hStyle: "neat",
		pubicHStyle: "waxed",
		boobs: 650,
		butt: 4,
		vagina: 1,
		vaginaLube: 1,
		preg: -2,
		anus: 1,
		ovaries: 1,
		skill: {vaginal: 35, oral: 35, anal: 35},
		attrXX: 80,
		attrXY: 40,
		fetishKnown: 1,
		lipsTat: "Purple grapes are tattooed on $his face.",
		buttTat: "Purple grapes are tattooed on $his buttocks.",
		mother: -9995,
		father: -9994,
		piercing: {nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}},
		intelligence: -60
	},
	/* vibe nips, implant link to sister */
	{
		ID: 700008,
		slaveName: "Apple",
		birthName: "Apple",
		actualAge: 28,
		physicalAge: 28,
		visualAge: 28,
		ovaryAge: 28,
		health: {condition: 20},
		devotion: 75,
		muscles: 20,
		race: "white",
		eye: {origColor: "dark brown"},
		pubicHColor: "black",
		origSkin: "pale",
		origHColor: "black",
		hLength: 60,
		hStyle: "neat",
		pubicHStyle: "waxed",
		boobs: 500,
		butt: 3,
		lips: 55,
		lipsTat: "permanent makeup",
		vagina: 3,
		vaginaLube: 1,
		preg: -2,
		ovaries: 1,
		skill: {vaginal: 15, oral: 35},
		vaginalAccessory: "large dildo",
		buttplug: "large plug",
		attrXY: 40,
		fetish: "submissive",
		fetishKnown: 1,
		custom: {tattoo: "Cored apples are tattooed on $his face."},
		buttTat: "Cored apples are tattooed on $his buttocks.",
		intelligence: -60,
		piercing: {nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}},
	},
	/* vibe nips, stupid, sensitive, no masturbation implant*/
];

/**
 * @type {FC.SlaveTemplate[]}
 */
App.Data.HeroSlaves.DFextreme = [
	{
		ID: 700009,
		slaveName: "Plum",
		birthName: "Plum",
		actualAge: 28,
		physicalAge: 28,
		visualAge: 28,
		ovaryAge: 28,
		health: {condition: 20},
		devotion: 75,
		muscles: 30,
		weight: 20,
		race: "white",
		eye: {origColor: "brown"},
		origHColor: "brown",
		origSkin: "pale",
		hLength: 10,
		hStyle: "wavy",
		pubicHStyle: "waxed",
		boobs: 400,
		butt: 2,
		lips: 35,
		vagina: 5,
		vaginaLube: 1,
		preg: -2,
		anus: 2,
		ovaries: 1,
		skill: {vaginal: 15, oral: 15, anal: 15},
		buttplug: "large plug",
		attrXY: 40,
		fetishKnown: 1,
		lipsTat: "Cored plums are tattooed on $his face.",
		buttTat: "Cored plums are tattooed on $his buttocks.",
		piercing: {
			nipple: {weight: 1}, vagina: {weight: 2}, genitals: {weight: 2}, corset: {weight: 1, desc: "$He has massive C-clamp piercings in $his back that allow $him to act as furniture"}
		},
		sexualFlaw: "self hating",
		clothes: "no clothing",
		vaginalAccessory: "long, huge dildo"
	},
	/* vibe nips, can act as furniture*/
];
