globalThis.MpregSelf = function() {
	const node = new DocumentFragment();
	let r = [];
	const {
		HeU,
		heU, himU, hisU, girlU
	} = getNonlocalPronouns(V.seeDicks).appendSuffix("U");

	if (V.PC.counter.birthSelf === 0) {
		if (V.PC.balls >= 14) {
			r.push(`Calling over your closest slave, you order ${himU} to bring you one of the high-volume enema syringes from the slave quarters. ${HeU} rushes off, and you set about getting naked before lying down on your luxurious bed. Your cock is already rock-hard, sending rivulets of precum running down to pool on your massive balls. Your pussy is similarly soaked, imagining your latest deviancy has it practically puddling. Just as you start to think about punishing your slave for taking too long, you hear a knock before ${heU} enters carrying the extra-long enema syringe. Impatient, you give ${himU} your instructions: "Pull out the plunger and keep the syringe handy. You're going to suck me off, but I want every drop of my cum to go into that syringe. No spilling. Now get started."`);
			r.push(`Following your instructions, ${heU} eagerly drops to ${hisU} knees and inhales your soaked member. The large volume of precum coming from your engorged prostate necessitates frequent swallowing that only adds to your pleasure. You lay back and enjoy yourself as ${heU} massages your massive balls before slipping ${hisU} hand underneath to start fingering your soaked pussy. The expert ministrations from your slave combine with your thoughts of what comes next, and soon your sack is clenching your massive balls as your body prepares to cum. Recognizing the signs, your slave removes ${hisU} mouth and replaces it with the open end of the syringe. ${HeU} takes ${hisU} sodden hand from your cunt and starts stroking vigorously, and soon you're spraying inhumanly large jets of alabaster cum into the enema syringe. It's good that you asked for high-capacity version, as the prodigious quantity of fertile semen would have overflowed from a smaller container.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`You sit up and pick up the previously discarded plunger while your slave continues to hold the syringe. ${HeU} has thoughtfully blocked the tip with the palm of ${hisU} hand, keeping any of the precious fluid from escaping. You position the plunger and barely insert it into the open syringe, not wanting to accidentally force out your semen. The two of you flip the full syringe over so that the business end is pointing upward, and the slave removes ${hisU} hand while you make sure the plunger is secure and won't leak any of the precious cargo. Your slave eagerly licks the drop of cum off the palm of ${hisU} hand, but you don't begrudge ${himU} a small treat. Instead, you get a firm grasp on the glass of the thick enema syringe and lay back once more.`);
			r.push(`You spread your legs into a wide "M" shape, as if preparing for a gynecological exam. You can't demean yourself by allowing your slave to penetrate you, so you carefully position the girthy syringe between your massive balls and slowly shove it into your pussy. Adjusting your grip, you keep pushing; you're unable to suppress a moan when you feel the nubby plug-like tip knock at the entrance of your womb. Thoroughly penetrated, you lay back and give your slave instructions: "Fuck me good and hard with the syringe until I cum. When I do, I want you to take both hands and ram that plunger in. Push hard, I want that syringe completely empty when you're done."`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`The ${girlU} does as ${heU}'s told, getting a firm grip on the syringe and pushing in slightly before drawing it outward. After a brief pause, ${heU} shoves it back inside you. Seeing the undeniable pleasure on your face, ${heU} takes it as permission to continue and quickly picks up the pace. Soon ${heU}'s fucking you hard and fast with the syringe. Thanks to the position caused by your widely-splayed legs, your fertile womb is lined up perfectly for each thrust to slam the pointy enema bulb into the opening of your cervix, forcibly stretching it further open with each piercing impact. The sensation is too much to bear after having cum so recently, and you rapidly moan your way towards another orgasm.`);
			r.push(`Your fevered thoughts are focused on the perverse pleasure of giving yourself a creampie, intensifying the extreme pleasure you're feeling. Soon you are cumming with a scream of ecstasy, your neglected cock making your orgasm obvious as it sends thick streams of cum spraying all over the place to soak you and your slave. Seeing ${hisU} cue, the ${girlU} grabs the large plunger with both hands and starts shoving it in the direction of your womb. ${HeU} leans in, using ${hisU} body weight to help fight the resistance of your richly-thick and fertile semen that's filling the syringe. The pressure forces the whole enema syringe further inside you, causing a blissful stretching sensation as the squirting enema bulb penetrates your cervix to lodge in your womb.`);
			r.push(`Your orgasm continues unabated, spurred on by the syringe now spraying your cum directly into your womb. You spend a couple minutes that feel like hours cumming as your slave slowly inflates your womb with a seemingly-endless volume of your virile cum.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`Sometime later when you've recovered your senses, you see your slave standing by while holding the plunger to keep your balloon-like womb from forcing its meal back into the syringe. The nearly 2 liters of cum you have stuffed inside you leaves your stomach looking noticeably distended, prompting you to rub your sloshing belly. You give the waiting ${girlU} ${hisU} orders: "Pull it out, and use your mouth to keep the mess to a minimum." ${HeU} gets on ${hisU} knees and takes a firm grip on the syringe before peering over your inflated belly to make sure you're ready for ${himU} to continue. As soon as you give ${himU} a nod ${heU} pulls, and with a popping sensation the enema bulb comes free. The sudden lack of resistance causes ${himU} to swiftly yank the rest of the syringe out of you, opening the floodgates for the colossal quantity of cum inflating your womb. Your well-trained slave reacts quickly, hefting your massive balls up and out of the way so ${heU} can catch the torrent of jizz that's just starting to pour from your cunt.`);
			r.push(`You hear some wet sounds as ${heU} slurps down the cum that already escaped, and then you feel ${hisU} soft lips pressed to your vulva as ${heU} steadfastly works to drink the unending flood of semen. You relax and enjoy the afterglow of your orgasms while ${heU} works, proud of your ingenious idea to take advantage of your inhuman sperm production. There's always the tap from ${V.dairyName} of course, but this way you don't have to worry about getting pregnant. That last thought gives you pause. You can't get yourself pregnant... right?`);
		} else if (V.PC.balls >= 9) {
			r.push(`Calling over your closest slave, you order ${himU} to bring you one of the enema syringes from the slave quarters. ${HeU} rushes off, and you set about getting naked before lying down on your luxurious bed. Your cock is already rock-hard, sending a steady stream of precum running down to pool on your huge balls. Your pussy is similarly soaked, imagining your latest deviancy has it practically puddling. Just as you start to think about punishing your slave for taking too long, you hear a knock before ${heU} enters carrying the glass enema syringe. Impatient, you give ${himU} your instructions: "Pull out the plunger and keep the syringe handy. You're going to suck me off, but I want every drop of my cum to go into that syringe. No spilling. Now get started."`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`Following your instructions, ${heU} eagerly drops to ${hisU} knees and inhales your soaked member. The large volume of precum coming from your swollen prostate necessitates regular swallowing that only adds to your pleasure. You lay back and enjoy yourself as ${heU} massages your huge balls before slipping ${hisU} hand underneath to start fingering your soaked pussy. The expert ministrations from your slave combine with your thoughts of what comes next, and soon your sack is clenching your huge balls as your body prepares to cum. Recognizing the signs, your slave removes ${hisU} mouth and replaces it with the open end of the syringe. ${HeU} takes ${hisU} sodden hand from your cunt and starts stroking vigorously, and soon you're spraying massive jets of alabaster cum into the enema syringe. It's good that you decided on an enema syringe instead of a normal dildo suppository, as the huge quantity of fertile semen would have overflowed from a smaller container.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`You sit up and pick up the previously discarded plunger while your slave continues to hold the syringe. ${HeU} has thoughtfully blocked the tip with the palm of ${hisU} hand, keeping any of the precious fluid from escaping. You position the plunger and barely insert it into the open syringe, not wanting to accidentally force out your semen. The two of you flip the full syringe over so that the business end is pointing upward, and the slave removes ${hisU} hand while you make sure the plunger is secure and won't leak any of the precious cargo. Your slave eagerly licks the drop of cum off the palm of ${hisU} hand, but you don't begrudge ${himU} a small treat. Instead, you get a firm grasp on the glass of the thick enema syringe and lay back once more.`);
			r.push(`You spread your legs into a wide "M" shape, as if preparing for a gynecological exam. You can't demean yourself by allowing your slave to penetrate you, so you carefully position the girthy syringe between your huge balls and slowly shove it into your pussy. Adjusting your grip, you keep pushing; you're unable to suppress a moan when you feel the nubby plug-like tip knock at the entrance of your womb. Thoroughly penetrated, you lay back and give your slave instructions: "Fuck me good and hard with the syringe until I cum. When I do, I want you to take both hands and ram that plunger in. Push hard, I want that syringe completely empty when you're done."`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`The ${girlU} does as ${heU}'s told, getting a firm grip on the syringe and pushing in slightly before drawing it outward. After a brief pause, ${heU} shoves it back inside you. Seeing the undeniable pleasure on your face, ${heU} takes it as permission to continue and quickly picks up the pace. Soon ${heU}'s fucking you hard and fast with the syringe. Thanks to the position caused by your widely-splayed legs, your fertile womb is lined up perfectly for each thrust to slam the pointy enema bulb into the opening of your cervix, forcibly stretching it further open with each piercing impact. The sensation is too much to bear after having cum so recently, and you rapidly moan your way towards another orgasm.`);
			r.push(`Your fevered thoughts are focused on the perverse pleasure of giving yourself a creampie, intensifying the extreme pleasure you're feeling. Soon you are cumming with a scream of ecstasy, your neglected cock making your orgasm obvious as it sends thick streams of cum spraying all over the place to coat you and your slave. Seeing ${hisU} cue, the ${girlU} grabs the large plunger with both hands and starts shoving it in the direction of your womb. ${HeU} leans in, using ${hisU} body weight to help fight the resistance of your richly-thick and fertile semen that's filling the syringe. The pressure forces the whole enema syringe further inside you, causing a blissful stretching sensation as the squirting enema bulb penetrates your cervix to lodge in your womb.`);
			r.push(`Your orgasm continues unabated, spurred on by the syringe now spraying your cum directly into your womb. You spend a couple minutes that feel like hours cumming as your slave slowly inflates your womb with a liter of your virile cum.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`Sometime later when you've recovered your senses, you see your slave standing by while holding the plunger to keep your stuffed womb from forcing its meal back into the syringe. You give the waiting ${girlU} ${hisU} orders: "Pull it out, and use your mouth to keep the mess to a minimum." ${HeU} gets on ${hisU} knees and takes a firm grip on the syringe before peering over your swollen belly to make sure you're ready for ${himU} to continue. As soon as you give ${himU} a nod ${heU} pulls, and with a popping sensation the enema bulb comes free. The sudden lack of resistance causes ${himU} to swiftly yank the rest of the syringe out of you, opening the floodgates for the huge quantity of cum that's stuffed in your womb. Your well-trained slave reacts quickly, hefting your huge balls up and out of the way so ${heU} can catch the torrent of jizz that's just starting to pour from your cunt.`);
			r.push(`You hear some wet sounds as ${heU} slurps down the cum that already escaped, and then you feel ${hisU} soft lips pressed to your vulva as ${heU} steadfastly works to drink the unending flood of semen. You relax and enjoy the afterglow of your orgasms while ${heU} works, proud of your ingenious idea to take advantage of your prodigious sperm production. There's always the tap from ${V.dairyName} of course, but this way you don't have to worry about getting pregnant. That last thought gives you pause. You can't get yourself pregnant... right?`);
		} else if (V.PC.balls >= 5) {
			r.push(`Calling over your closest slave, you order ${himU} to bring you one of the dildo-shaped suppository syringes from the slave quarters. ${HeU} rushes off, and you set about getting naked before lying down on your luxurious bed. Your cock is already rock-hard, sending regular drips of precum running down onto your large balls. Your pussy is similarly soaked, imagining your latest deviancy has it practically puddling. Just as you start to think about punishing your slave for taking too long, you hear a knock before ${heU} enters carrying the remarkably-lifelike dildo syringe. Impatient, you give ${himU} your instructions: "Pull out the plunger and keep the syringe handy. You're going to suck me off, but I want every drop of my cum to go into that syringe. No spilling. Now get started."`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`Following your instructions, ${heU} eagerly drops to ${hisU} knees and inhales your straining cock. The extra precum coming from your enhanced prostate necessitates occasional swallowing that only adds to your pleasure. You lay back and enjoy yourself as ${heU} massages your large balls before slipping ${hisU} hand underneath to start fingering your soaked pussy. The expert ministrations from your slave combine with your thoughts of what comes next, and soon your sack is clenching your large balls as your body prepares to cum. Recognizing the signs, your slave removes ${hisU} mouth and replaces it with the open end of the syringe. ${HeU} takes ${hisU} sodden hand from your cunt and starts stroking vigorously, and soon you're spraying large jets of alabaster cum into the syringe. It's close, the large quantity of fertile semen almost overflowing from the dildo suppository.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`You sit up and pick up the previously discarded plunger while your slave continues to hold the syringe. ${HeU} has thoughtfully blocked the tip with the palm of ${hisU} hand, keeping any of the precious fluid from escaping. You position the plunger and barely insert it into the open syringe, not wanting to accidentally force out your semen. The two of you flip the full syringe over so that the business end is pointing upward, and the slave removes ${hisU} hand while you make sure the plunger is secure and won't leak any of the precious cargo. Your slave eagerly licks the drop of cum off the palm of ${hisU} hand, but you don't begrudge ${himU} a small treat. Instead, you get a firm grasp on the silicone of the thick dildo syringe and lay back once more.`);
			r.push(`You spread your legs into a wide "M" shape, as if preparing for a gynecological exam. You can't demean yourself by allowing your slave to penetrate you, so you carefully position the girthy syringe underneath your large balls and slowly shove it into your pussy. Adjusting your grip, you keep pushing; you're unable to suppress a moan when you feel the cock-like tip knock at the entrance of your womb. Thoroughly penetrated, you lay back and give your slave instructions: "Fuck me good and hard with the syringe until I cum. When I do, I want you to ram that plunger in. Push hard, I want that syringe completely empty when you're done."`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`The ${girlU} does as ${heU}'s told, getting a firm grip on the syringe and pushing in slightly before drawing it outward. After a brief pause, ${heU} shoves it back inside you. Seeing the undeniable pleasure on your face, ${heU} takes it as permission to continue and quickly picks up the pace. Soon ${heU}'s fucking you hard and fast with the syringe. Thanks to the position caused by your widely-splayed legs, your fertile womb is lined up perfectly for each thrust to slam the head of the dildo into your cervix, battering it open with each impact. The sensation is too much to bear after having cum so recently, and you rapidly moan your way towards another orgasm.`);
			r.push(`Your fevered thoughts are focused on the perverse pleasure of giving yourself a creampie, intensifying the extreme pleasure you're feeling. Soon you are cumming with a scream of ecstasy, your neglected cock making your orgasm obvious as it sends jets of cum all over the place to land on you and your slave. Seeing ${hisU} cue, the ${girlU} grabs the large plunger and starts shoving it in the direction of your womb. ${HeU} pushes hard to help fight the resistance of your richly-thick and fertile semen that's filling the syringe. The pressure forces the silicone cockhead against your cervix, creating a seal and leaving the syringe free to spray your semen through your battered cervix and into your hungry womb.`);
			r.push(`Your orgasm continues unabated, spurred on by warm fluid flowing into your womb. You spend a minute that feel like an hour cumming as your slave slowly fills your womb with a few deciliters of virile cum.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`Sometime later when you've recovered your senses, you see your slave standing by while holding the dildo inside you to keep you plugged up. You give the waiting ${girlU} ${hisU} orders: "Pull it out, and use your mouth to keep the mess to a minimum." ${HeU} gets on ${hisU} knees and takes a firm grip on the syringe before peering up at you to make sure you're ready for ${himU} to continue. As soon as you give ${himU} a nod ${heU} pulls the dildo free, opening the floodgates for the cum that's filling your womb. Your well-trained slave reacts quickly, lifting your large balls up and out of the way so ${heU} can catch the stream of jizz that's just starting to pour from your cunt.`);
			r.push(`You hear some wet sounds as ${heU} slurps down the cum that already escaped, and then you feel ${hisU} soft lips pressed to your vulva as ${heU} steadfastly works to drink the escaping semen. You relax and enjoy the afterglow of your orgasms while ${heU} works, proud of your ingenious idea to take advantage of your considerable sperm production. There's always the tap from ${V.dairyName} of course, but this way you don't have to worry about getting pregnant. That last thought gives you pause. You can't get yourself pregnant... right?`);
		} else {
			r.push(`Calling over your closest slave, you order ${himU} to bring you one of the dildo-shaped suppository syringes from the slave quarters. ${HeU} rushes off, and you set about getting naked before lying down on your luxurious bed. Your cock is already rock-hard, a large droplet of precum hanging from the head. Your pussy is similarly soaked, imagining your latest deviancy has it practically puddling. Just as you start to think about punishing your slave for taking too long, you hear a knock before ${heU} enters carrying the remarkably-lifelike dildo syringe. Impatient, you give ${himU} your instructions: "Pull out the plunger and keep the syringe handy. You're going to suck me off, but I want every drop of my cum to go into that syringe. No spilling. Now get started."`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`Following your instructions, ${heU} eagerly drops to ${hisU} knees and inhales your straining cock. You lay back and enjoy yourself as ${heU} massages your balls before slipping ${hisU} hand downward to start fingering your soaked pussy. The expert ministrations from your slave combine with your thoughts of what comes next, and soon your sack is clenching tightly as your body prepares to cum. Recognizing the signs, your slave removes ${hisU} mouth and replaces it with the open end of the syringe. ${HeU} takes ${hisU} sodden hand from your cunt and starts stroking vigorously, and soon you're spraying jets of alabaster cum into the syringe. It's a powerful orgasm, but you only manage to fill a quarter of it.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`You sit up and pick up the previously discarded plunger while your slave continues to hold the syringe. ${HeU} has thoughtfully blocked the tip with the palm of ${hisU} hand, keeping any of the precious fluid from escaping. You position the plunger and barely insert it into the open syringe, not wanting to accidentally force out your semen. The two of you flip the syringe over so that the business end is pointing upward, and the slave removes ${hisU} hand while you make sure the plunger is inserted far enough that you've gotten all the air out of the syringe. Your slave eagerly licks the drop of cum off the palm of ${hisU} hand, but you don't begrudge ${himU} a small treat. Instead, you get a firm grasp on the silicone of the thick dildo syringe and lay back once more.`);
			r.push(`You spread your legs into a wide "M" shape, as if preparing for a gynecological exam. You can't demean yourself by allowing your slave to penetrate you, so you carefully position the girthy syringe underneath your balls and slowly shove it into your pussy. Adjusting your grip, you keep pushing; you're unable to suppress a moan when you feel the cock-like tip knock at the entrance of your womb. Thoroughly penetrated, you lay back and give your slave instructions: "Fuck me good and hard with the syringe until I cum. When I do, I want you to ram that plunger in. I want that syringe completely empty when you're done."`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`The ${girlU} does as ${heU}'s told, getting a firm grip on the syringe and pushing in slightly before drawing it outward. After a brief pause, ${heU} shoves it back inside you. Seeing the undeniable pleasure on your face, ${heU} takes it as permission to continue and quickly picks up the pace. Soon ${heU}'s fucking you hard and fast with the syringe. Thanks to the position caused by your widely-splayed legs, your fertile womb is lined up perfectly for each thrust to slam the head of the dildo into your cervix, battering it open with each impact. The sensation is too much to bear after having cum so recently, and you rapidly moan your way towards another orgasm.`);
			r.push(`Your fevered thoughts are focused on the perverse pleasure of giving yourself a creampie, intensifying the extreme pleasure you're feeling. Soon you are cumming with a scream of ecstasy, your neglected cock making your orgasm obvious as it sends several jets of cum to land on your reclined body. Seeing ${hisU} cue, the ${girlU} grabs the large plunger and starts shoving it in the direction of your womb. ${HeU} pushes hard to help fight the resistance of your richly-thick and fertile semen that's filling the syringe. The pressure forces the silicone cockhead against your cervix, creating a seal and leaving the syringe free to spray your semen through your battered cervix and into your hungry womb.`);
			r.push(`Your orgasm continues unabated, spurred on by the jet of fluid flowing into your womb. Your orgasm soon fades, and you wish that you could produce more than a deciliter of cum to fill yourself with.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`Now that your orgasm is over, you notice your slave standing by while holding the dildo inside you to keep you plugged up. You give the waiting ${girlU} ${hisU} orders: "Pull it out, and use your mouth to keep the mess to a minimum." ${HeU} gets on ${hisU} knees and takes a firm grip on the syringe before peering up at you to make sure you're ready for ${himU} to continue. As soon as you give ${himU} a nod ${heU} pulls the dildo free, allowing the cum inside you to leak out. Your well-trained slave reacts quickly, lifting your balls up and out of the way so ${heU} can catch the load of jizz before it starts to leak out of your cunt.`);
			r.push(`You feel ${hisU} soft lips pressed to your vulva as ${heU} works to retrieve ${hisU} treat. You hear some soft slurping noises and feel a warm tongue worming its way inside you to retrieve any lingering cum. You relax and enjoy the afterglow of your orgasms while ${heU} works, proud of your ingenious idea to take advantage of your own balls for a satisfying creampie. There's always a slave to do that, of course, but this way you don't have to worry about getting pregnant. That last thought gives you pause. You can't get yourself pregnant... right?`);
		}
		let selfPreg = 30+(V.PC.balls*3);
		r.push(knockMeUp(V.PC, selfPreg, 0, -1));
	} else {
		if (V.PC.balls >= 14) {
			r.push(`Calling over your closest slave, you order ${himU} to bring you one of the high-volume enema syringes from the slave quarters. ${HeU} rushes off, and you set about getting naked before lying down on your luxurious bed. Your cock is already rock-hard, sending rivulets of precum running down to pool on your massive balls. Your pussy is similarly soaked, imagining your belly swelling after you knock yourself up has it practically puddling. Just as you start to think about punishing your slave for taking too long, you hear a knock before ${heU} enters carrying the extra-long enema syringe. Impatient, you give ${himU} your instructions: "Pull out the plunger and keep the syringe handy. You're going to suck me off, but I want every drop of my cum to go into that syringe. No spilling. Now get started."`);
			r.push(`Following your instructions, ${heU} eagerly drops to ${hisU} knees and inhales your soaked member. The large volume of precum coming from your engorged prostate necessitates frequent swallowing that only adds to your pleasure. You lay back and enjoy yourself as ${heU} massages your massive balls before slipping ${hisU} hand underneath to start fingering your soaked pussy. The expert ministrations from your slave combine with your thoughts of the semi-incestuous stuffing that comes next, and soon your sack is clenching your massive balls as your body prepares to cum. Recognizing the signs, your slave removes ${hisU} mouth and replaces it with the open end of the syringe. ${HeU} takes ${hisU} sodden hand from your cunt and starts stroking vigorously, and soon you're spraying inhumanly large jets of alabaster cum into the enema syringe. It's good that you asked for high-capacity version, as the prodigious quantity of fertile semen would have overflowed from a smaller container.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`You sit up and pick up the previously discarded plunger while your slave continues to hold the syringe. ${HeU} has thoughtfully blocked the tip with the palm of ${hisU} hand, keeping any of the precious fluid from escaping. You position the plunger and barely insert it into the open syringe, not wanting to accidentally force out your semen. The two of you flip the full syringe over so that the business end is pointing upward, and the slave removes ${hisU} hand while you make sure the plunger is secure and won't leak any of the precious cargo. Your slave eagerly licks the drop of cum off the palm of ${hisU} hand, but you don't begrudge ${himU} a small treat. Instead, you get a firm grasp on the glass of the thick enema syringe and lay back once more.`);
			r.push(`You spread your legs into a wide "M" shape, as if preparing for a gynecological exam. You can't demean yourself by allowing your slave to penetrate you, so you carefully position the girthy syringe between your massive balls and slowly shove it into your pussy. Adjusting your grip, you keep pushing; you're unable to suppress a moan when you feel the nubby plug-like tip knock at the entrance of your womb. Thoroughly penetrated, you lay back and give your slave instructions: "Fuck me good and hard with the syringe until I cum. When I do, I want you to take both hands and ram that plunger in. Push hard, I want that syringe completely empty when you're done."`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`The ${girlU} does as ${heU}'s told, getting a firm grip on the syringe and pushing in slightly before drawing it outward. After a brief pause, ${heU} shoves it back inside you. Seeing the undeniable pleasure on your face, ${heU} takes it as permission to continue and quickly picks up the pace. Soon ${heU}'s fucking you hard and fast with the syringe. Thanks to the position caused by your widely-splayed legs, your fertile womb is lined up perfectly for each thrust to slam the pointy enema bulb into the opening of your cervix, forcibly stretching it further open with each piercing impact. The sensation is too much to bear after having cum so recently, and you rapidly moan your way towards another orgasm.`);
			r.push(`Your fevered thoughts are focused on the perverse pleasure of giving yourself a creampie, intensifying the extreme pleasure you're feeling. Soon you are cumming with a scream of ecstasy, your neglected cock making your orgasm obvious as it sends thick streams of cum spraying all over the place to soak you and your slave. Seeing ${hisU} cue, the ${girlU} grabs the large plunger with both hands and starts shoving it in the direction of your womb. ${HeU} leans in, using ${hisU} body weight to help fight the resistance of your richly-thick and fertile semen that's filling the syringe. The pressure forces the whole enema syringe further inside you, causing a blissful stretching sensation as the squirting enema bulb penetrates your cervix to lodge in your womb.`);
			r.push(`Your orgasm continues unabated, spurred on by the syringe now spraying your cum directly into your womb. You spend a couple minutes that feel like hours cumming as your slave slowly inflates your womb with a seemingly-endless volume of your virile cum.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`Sometime later when you've recovered your senses, you see your slave standing by while holding the plunger to keep your balloon-like womb from forcing its meal back into the syringe. The nearly 2 liters of cum you have stuffed inside you leaves your stomach looking noticeably distended, prompting you to rub your sloshing belly. You give the waiting ${girlU} ${hisU} orders: "Pull it out, and use your mouth to keep the mess to a minimum." ${HeU} gets on ${hisU} knees and takes a firm grip on the syringe before peering over your inflated belly to make sure you're ready for ${himU} to continue. As soon as you give ${himU} a nod ${heU} pulls, and with a popping sensation the enema bulb comes free. The sudden lack of resistance causes ${himU} to swiftly yank the rest of the syringe out of you, opening the floodgates for the colossal quantity of cum inflating your womb. Your well-trained slave reacts quickly, hefting your massive balls up and out of the way so ${heU} can catch the torrent of jizz that's just starting to pour from your cunt.`);
			r.push(`You hear some wet sounds as ${heU} slurps down the cum that already escaped, and then you feel ${hisU} soft lips pressed to your vulva as ${heU} steadfastly works to drink the unending flood of semen. You relax and enjoy the afterglow of your orgasms while ${heU} works, proud of your ingenious idea to take advantage of your inhuman sperm production. There's always the tap from ${V.dairyName} of course, but why use slave cum when you have such obviously superior material available?`);
		} else if (V.PC.balls >= 9) {
			r.push(`Calling over your closest slave, you order ${himU} to bring you one of the enema syringes from the slave quarters. ${HeU} rushes off, and you set about getting naked before lying down on your luxurious bed. Your cock is already rock-hard, sending a steady stream of precum running down to pool on your huge balls. Your pussy is similarly soaked, imagining your belly swelling after you knock yourself up has it practically puddling. Just as you start to think about punishing your slave for taking too long, you hear a knock before ${heU} enters carrying the glass enema syringe. Impatient, you give ${himU} your instructions: "Pull out the plunger and keep the syringe handy. You're going to suck me off, but I want every drop of my cum to go into that syringe. No spilling. Now get started."`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`Following your instructions, ${heU} eagerly drops to ${hisU} knees and inhales your soaked member. The large volume of precum coming from your swollen prostate necessitates regular swallowing that only adds to your pleasure. You lay back and enjoy yourself as ${heU} massages your huge balls before slipping ${hisU} hand underneath to start fingering your soaked pussy. The expert ministrations from your slave combine with your thoughts of the semi-incestuous stuffing that comes next, and soon your sack is clenching your huge balls as your body prepares to cum. Recognizing the signs, your slave removes ${hisU} mouth and replaces it with the open end of the syringe. ${HeU} takes ${hisU} sodden hand from your cunt and starts stroking vigorously, and soon you're spraying massive jets of alabaster cum into the enema syringe. It's good that you decided on an enema syringe instead of a normal dildo suppository, as the huge quantity of fertile semen would have overflowed from a smaller container.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`You sit up and pick up the previously discarded plunger while your slave continues to hold the syringe. ${HeU} has thoughtfully blocked the tip with the palm of ${hisU} hand, keeping any of the precious fluid from escaping. You position the plunger and barely insert it into the open syringe, not wanting to accidentally force out your semen. The two of you flip the full syringe over so that the business end is pointing upward, and the slave removes ${hisU} hand while you make sure the plunger is secure and won't leak any of the precious cargo. Your slave eagerly licks the drop of cum off the palm of ${hisU} hand, but you don't begrudge ${himU} a small treat. Instead, you get a firm grasp on the glass of the thick enema syringe and lay back once more.`);
			r.push(`You spread your legs into a wide "M" shape, as if preparing for a gynecological exam. You can't demean yourself by allowing your slave to penetrate you, so you carefully position the girthy syringe between your huge balls and slowly shove it into your pussy. Adjusting your grip, you keep pushing; you're unable to suppress a moan when you feel the nubby plug-like tip knock at the entrance of your womb. Thoroughly penetrated, you lay back and give your slave instructions: "Fuck me good and hard with the syringe until I cum. When I do, I want you to take both hands and ram that plunger in. Push hard, I want that syringe completely empty when you're done."`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`The ${girlU} does as ${heU}'s told, getting a firm grip on the syringe and pushing in slightly before drawing it outward. After a brief pause, ${heU} shoves it back inside you. Seeing the undeniable pleasure on your face, ${heU} takes it as permission to continue and quickly picks up the pace. Soon ${heU}'s fucking you hard and fast with the syringe. Thanks to the position caused by your widely-splayed legs, your fertile womb is lined up perfectly for each thrust to slam the pointy enema bulb into the opening of your cervix, forcibly stretching it further open with each piercing impact. The sensation is too much to bear after having cum so recently, and you rapidly moan your way towards another orgasm.`);
			r.push(`Your fevered thoughts are focused on the perverse pleasure of giving yourself a creampie, intensifying the extreme pleasure you're feeling. Soon you are cumming with a scream of ecstasy, your neglected cock making your orgasm obvious as it sends thick streams of cum spraying all over the place to coat you and your slave. Seeing ${hisU} cue, the ${girlU} grabs the large plunger with both hands and starts shoving it in the direction of your womb. ${HeU} leans in, using ${hisU} body weight to help fight the resistance of your richly-thick and fertile semen that's filling the syringe. The pressure forces the whole enema syringe further inside you, causing a blissful stretching sensation as the squirting enema bulb penetrates your cervix to lodge in your womb.`);
			r.push(`Your orgasm continues unabated, spurred on by the syringe now spraying your cum directly into your womb. You spend a couple minutes that feel like hours cumming as your slave slowly inflates your womb with a full liter of your virile cum.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`Sometime later when you've recovered your senses, you see your slave standing by while holding the plunger to keep your stuffed womb from forcing its meal back into the syringe. You give the waiting ${girlU} ${hisU} orders: "Pull it out, and use your mouth to keep the mess to a minimum." ${HeU} gets on ${hisU} knees and takes a firm grip on the syringe before peering over your swollen belly to make sure you're ready for ${himU} to continue. As soon as you give ${himU} a nod ${heU} pulls, and with a popping sensation the enema bulb comes free. The sudden lack of resistance causes ${himU} to swiftly yank the rest of the syringe out of you, opening the floodgates for the huge quantity of cum that's stuffed in your womb. Your well-trained slave reacts quickly, hefting your huge balls up and out of the way so ${heU} can catch the torrent of jizz that's just starting to pour from your cunt.`);
			r.push(`You hear some wet sounds as ${heU} slurps down the cum that already escaped, and then you feel ${hisU} soft lips pressed to your vulva as ${heU} steadfastly works to drink the unending flood of semen. You relax and enjoy the afterglow of your orgasms while ${heU} works, proud of your ingenious idea to take advantage of your prodigious sperm production. There's always the tap from ${V.dairyName} of course, but why use slave cum when you have such obviously superior material available?`);
		} else if (V.PC.balls >= 5) {
			r.push(`Calling over your closest slave, you order ${himU} to bring you one of the dildo-shaped suppository syringes from the slave quarters. ${HeU} rushes off, and you set about getting naked before lying down on your luxurious bed. Your cock is already rock-hard, sending regular drips of precum running down onto your large balls. Your pussy is similarly soaked, imagining your belly swelling after you knock yourself up has it practically puddling. Just as you start to think about punishing your slave for taking too long, you hear a knock before ${heU} enters carrying the remarkably-lifelike dildo syringe. Impatient, you give ${himU} your instructions: "Pull out the plunger and keep the syringe handy. You're going to suck me off, but I want every drop of my cum to go into that syringe. No spilling. Now get started."`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`Following your instructions, ${heU} eagerly drops to ${hisU} knees and inhales your straining cock. The extra precum coming from your enhanced prostate necessitates occasional swallowing that only adds to your pleasure. You lay back and enjoy yourself as ${heU} massages your large balls before slipping ${hisU} hand underneath to start fingering your soaked pussy. The expert ministrations from your slave combine with your thoughts of the semi-incestuous stuffing that comes next, and soon your sack is clenching your large balls as your body prepares to cum. Recognizing the signs, your slave removes ${hisU} mouth and replaces it with the open end of the syringe. ${HeU} takes ${hisU} sodden hand from your cunt and starts stroking vigorously, and soon you're spraying large jets of alabaster cum into the syringe. It's close, the large quantity of fertile semen almost overflows from the dildo suppository.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`You sit up and pick up the previously discarded plunger while your slave continues to hold the syringe. ${HeU} has thoughtfully blocked the tip with the palm of ${hisU} hand, keeping any of the precious fluid from escaping. You position the plunger and barely insert it into the open syringe, not wanting to accidentally force out your semen. The two of you flip the full syringe over so that the business end is pointing upward, and the slave removes ${hisU} hand while you make sure the plunger is secure and won't leak any of the precious cargo. Your slave eagerly licks the drop of cum off the palm of ${hisU} hand, but you don't begrudge ${himU} a small treat. Instead, you get a firm grasp on the silicone of the thick dildo syringe and lay back once more.`);
			r.push(`You spread your legs into a wide "M" shape, as if preparing for a gynecological exam. You can't demean yourself by allowing your slave to penetrate you, so you carefully position the girthy syringe underneath your large balls and slowly shove it into your pussy. Adjusting your grip, you keep pushing; you're unable to suppress a moan when you feel the cock-like tip knock at the entrance of your womb. Thoroughly penetrated, you lay back and give your slave instructions: "Fuck me good and hard with the syringe until I cum. When I do, I want you to ram that plunger in. Push hard, I want that syringe completely empty when you're done."`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`The ${girlU} does as ${heU}'s told, getting a firm grip on the syringe and pushing in slightly before drawing it outward. After a brief pause, ${heU} shoves it back inside you. Seeing the undeniable pleasure on your face, ${heU} takes it as permission to continue and quickly picks up the pace. Soon ${heU}'s fucking you hard and fast with the syringe. Thanks to the position caused by your widely-splayed legs, your fertile womb is lined up perfectly for each thrust to slam the head of the dildo into your cervix, battering it open with each impact. The sensation is too much to bear after having cum so recently, and you rapidly moan your way towards another orgasm.`);
			r.push(`Your fevered thoughts are focused on the perverse pleasure of giving yourself a creampie, intensifying the extreme pleasure you're feeling. Soon you are cumming with a scream of ecstasy, your neglected cock making your orgasm obvious as it sends jets of cum all over the place to land on you and your slave. Seeing ${hisU} cue, the ${girlU} grabs the large plunger and starts shoving it in the direction of your womb. ${HeU} pushes hard to help fight the resistance of your richly-thick and fertile semen that's filling the syringe. The pressure forces the silicone cockhead against your cervix, creating a seal and leaving the syringe free to spray your semen through your battered cervix and into your hungry womb.`);
			r.push(`Your orgasm continues unabated, spurred on by warm fluid flowing into your womb. You spend a minute that feel like an hour cumming as your slave slowly fills your womb with a few deciliters of virile cum.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`Sometime later when you've recovered your senses, you see your slave standing by while holding the dildo inside you to keep you plugged up. You give the waiting ${girlU} ${hisU} orders: "Pull it out, and use your mouth to keep the mess to a minimum." ${HeU} gets on ${hisU} knees and takes a firm grip on the syringe before peering up at you to make sure you're ready for ${himU} to continue. As soon as you give ${himU} a nod ${heU} pulls the dildo free, opening the floodgates for the cum that's filling in your womb. Your well-trained slave reacts quickly, lifting your large balls up and out of the way so ${heU} can catch the stream of jizz that's just starting to pour from your cunt.`);
			r.push(`You hear some wet sounds as ${heU} slurps down the cum that already escaped, and then you feel ${hisU} soft lips pressed to your vulva as ${heU} steadfastly works to drink the escaping semen. You relax and enjoy the afterglow of your orgasms while ${heU} works, proud of your ingenious idea to take advantage of your considerable sperm production. There's always the tap from ${V.dairyName} of course, but why use slave cum when you have such obviously superior material available?`);
		} else {
			r.push(`Calling over your closest slave, you order ${himU} to bring you one of the dildo-shaped suppository syringes from the slave quarters. ${HeU} rushes off, and you set about getting naked before lying down on your luxurious bed. Your cock is already rock-hard, a large droplet of precum hanging from the head. Your pussy is similarly soaked, imagining your belly swelling after you knock yourself up has it practically puddling. Just as you start to think about punishing your slave for taking too long, you hear a knock before ${heU} enters carrying the remarkably-lifelike dildo syringe. Impatient, you give ${himU} your instructions: "Pull out the plunger and keep the syringe handy. You're going to suck me off, but I want every drop of my cum to go into that syringe. No spilling. Now get started."`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`Following your instructions, ${heU} eagerly drops to ${hisU} knees and inhales your straining cock. You lay back and enjoy yourself as ${heU} massages your balls before slipping ${hisU} hand downward to start fingering your soaked pussy. The expert ministrations from your slave combine with your thoughts of the semi-incestuous stuffing that comes next, and soon your sack is clenching tightly as your body prepares to cum. Recognizing the signs, your slave removes ${hisU} mouth and replaces it with the open end of the syringe. ${HeU} takes ${hisU} sodden hand from your cunt and starts stroking vigorously, and soon you're spraying jets of alabaster cum into the syringe. It's a powerful orgasm, but you only manage to fill a quarter of it.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`You sit up and pick up the previously discarded plunger while your slave continues to hold the syringe. ${HeU} has thoughtfully blocked the tip with the palm of ${hisU} hand, keeping any of the precious fluid from escaping. You position the plunger and barely insert it into the open syringe, not wanting to accidentally force out your semen. The two of you flip the syringe over so that the business end is pointing upward, and the slave removes ${hisU} hand while you make sure the plunger is inserted far enough that you've gotten all the air out of the syringe. Your slave eagerly licks the drop of cum off the palm of ${hisU} hand, but you don't begrudge ${himU} a small treat. Instead, you get a firm grasp on the silicone of the thick dildo syringe and lay back once more.`);
			r.push(`You spread your legs into a wide "M" shape, as if preparing for a gynecological exam. You can't demean yourself by allowing your slave to penetrate you, so you carefully position the girthy syringe underneath your balls and slowly shove it into your pussy. Adjusting your grip, you keep pushing; you're unable to suppress a moan when you feel the cock-like tip knock at the entrance of your womb. Thoroughly penetrated, you lay back and give your slave instructions: "Fuck me good and hard with the syringe until I cum. When I do, I want you to ram that plunger in. I want that syringe completely empty when you're done."`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`The ${girlU} does as ${heU}'s told, getting a firm grip on the syringe and pushing in slightly before drawing it outward. After a brief pause, ${heU} shoves it back inside you. Seeing the undeniable pleasure on your face, ${heU} takes it as permission to continue and quickly picks up the pace. Soon ${heU}'s fucking you hard and fast with the syringe. Thanks to the position caused by your widely-splayed legs, your fertile womb is lined up perfectly for each thrust to slam the head of the dildo into your cervix, battering it open with each impact. The sensation is too much to bear after having cum so recently, and you rapidly moan your way towards another orgasm.`);
			r.push(`Your fevered thoughts are focused on the perverse pleasure of giving yourself a creampie, intensifying the extreme pleasure you're feeling. Soon you are cumming with a scream of ecstasy, your neglected cock making your orgasm obvious as it sends several jets of cum to land on your reclined body. Seeing ${hisU} cue, the ${girlU} grabs the large plunger and starts shoving it in the direction of your womb. ${HeU} pushes hard to help fight the resistance of your richly-thick and fertile semen that's filling the syringe. The pressure forces the silicone cockhead against your cervix, creating a seal and leaving the syringe free to spray your semen through your battered cervix and into your hungry womb.`);
			r.push(`Your orgasm continues unabated, spurred on by the jet of fluid flowing into your womb. Your orgasm soon fades, and you wish that you could produce more than a deciliter of cum to fill yourself with.`);
			App.Events.addParagraph(node, r);
			r =[];
			r.push(`Now that your orgasm is over, you notice your slave standing by while holding the dildo inside you to keep you plugged up. You give the waiting ${girlU} ${hisU} orders: "Pull it out, and use your mouth to keep the mess to a minimum." ${HeU} gets on ${hisU} knees and takes a firm grip on the syringe before peering up at you to make sure you're ready for ${himU} to continue. As soon as you give ${himU} a nod ${heU} pulls the dildo free, allowing the cum inside you to leak out. Your well-trained slave reacts quickly, lifting your balls up and out of the way so ${heU} can catch the load of jizz before it starts to leak out of your cunt.`);
			r.push(`You feel ${hisU} soft lips pressed to your vulva as ${heU} works to retrieve ${hisU} treat. You hear some soft slurping noises and feel a warm tongue worming its way inside you to retrieve any lingering cum. You relax and enjoy the afterglow of your orgasms while ${heU} works, proud of your ingenious idea to take advantage of your own balls for a satisfying creampie. There's always a slave to do that, of course, but why use slave cum when you have such obviously superior material available?`);
		}
		r.push(knockMeUp(V.PC, 100, 0, -1));
	}
	App.Events.addParagraph(node, r);
	return node;
};
